### ISSUE TITLE
Error thrown in Chrome and Firefox at glminer.js line 261

### ISSUE THREAD

**Issue by viziionary** [howardc93/jsminer#3]
The line is

`gl.uniform2fv(hash1Loc, job.hash1);`

Chrome throws:

`Uncaught TypeError: Failed to execute 'uniform2fv' on 'WebGLRenderingContext': No function was found that matched the signature provided.
    at mine (glminer.js:262)`
Firefox throws:

`Argument 2 of WebGLRenderingContext.uniform2fv could not be converted to any of: Float32Array, UnrestrictedFloatSequence.`

Any idea on a fix?

**Comment by howardchung** [comment]
Sorry, unfortunately this project is no longer actively maintained.  I'd be happy to accept a PR if you find a fix though!
